
# cargo-vet audits file

[[audits.fastrand]]
who = "favonia <favonia@gmail.com>"
criteria = "safe-to-run"
delta = "2.3.0 -> 2.4.1"

[[audits.indexmap]]
who = "favonia <favonia@gmail.com>"
criteria = "safe-to-run"
delta = "2.13.0 -> 2.14.0"

[[audits.itoa]]
who = "favonia <favonia@gmail.com>"
criteria = "safe-to-run"
delta = "1.0.17 -> 1.0.18"

[[audits.proptest]]
who = "favonia <favonia@gmail.com>"
criteria = "safe-to-run"
delta = "1.10.0 -> 1.11.0"

[[audits.zerocopy-derive]]
who = "favonia <favonia@gmail.com>"
criteria = "safe-to-run"
delta = "0.8.42 -> 0.8.48"

[[trusted.hashbrown]]
criteria = "safe-to-deploy"
user-id = 55123             # rust-lang-owner
start = "2025-04-30"
end = "2027-04-10"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123             # rust-lang-owner
start = "2024-08-15"
end = "2027-04-10"
